run_tests: Make test failure more visible.

diff --git a/run_tests b/run_tests
--- a/run_tests
+++ b/run_tests
@@ -2,9 +2,14 @@
 
 nosetests3 -v || exit 1
 
+failed() {
+    echo "TESTS FAILED!"
+    exit 1
+}
+
 for f in tests/*.lst; do
     echo $f
-    ./apply_xform.py $f || exit 1
-    diff -u $f.exp.bb $f.out.bb || exit 1
-    diff -u $f.exp.dot $f.out.dot || exit 1
+    ./apply_xform.py $f || failed
+    diff -u $f.exp.bb $f.out.bb || failed
+    diff -u $f.exp.dot $f.out.dot || failed
 done
